import type { Language, SiteContent } from './types'

export const content: Record<Language, SiteContent> = {
  pt: {
    nav: { home: 'Home', about: 'Sobre', projects: 'Projetos' },
    home: {
      eyebrow: 'Software Engineer | Backend & Cloud',
      title: 'Engenharia de sistemas backend escaláveis',
      description:
        'Desenvolvo APIs, integrações e arquiteturas serverless para criar sistemas distribuídos executados em produção.',
      primaryAction: 'Ver projetos',
      secondaryAction: 'Entrar em contato',
      specialtiesLabel: 'Especialidades',
      specialtiesTitle: 'Tecnologia aplicada a problemas reais',
      specialties: [
        {
          title: 'Backend Engineering',
          description: 'APIs e serviços criados com clareza, confiabilidade e capacidade de evolução.',
          icon: 'backend',
        },
        {
          title: 'Cloud & AWS',
          description: 'Arquiteturas serverless e automações preparadas para operar em nuvem.',
          icon: 'cloud',
        },
        {
          title: 'Distributed Systems & Integrations',
          description: 'Sistemas orientados a eventos e integrações para criar fluxos confiáveis.',
          icon: 'systems',
        },
      ],
      featuredLabel: 'Projetos em destaque',
      featuredTitle: 'Uma seleção do meu trabalho',
      experienceLabel: 'Experiência resumida',
      experienceTitle: 'Aprendizado contínuo, entrega prática',
      experience:
        'Minha trajetória combina desenvolvimento, automação e integração de sistemas. Procuro compreender o contexto antes de escolher a tecnologia e valorizo soluções simples e sustentáveis.',
      contactLabel: 'Contato',
      contactTitle: 'Vamos construir algo juntos?',
      contact:
        'Estou disponível para conversar sobre projetos, oportunidades e boas ideias.',
    },
    about: {
      eyebrow: 'Sobre mim',
      title: 'Tecnologia com curiosidade, clareza e propósito.',
      journeyLabel: 'Trajetória',
      journeyTitle: 'Construindo uma visão completa',
      journey: [
        'Sou um desenvolvedor interessado em resolver problemas por meio da tecnologia. Gosto de compreender como cada parte de um sistema se conecta e como o software pode facilitar o trabalho das pessoas.',
        'A minha trajetória combina Python, cloud, integrações e desenvolvimento web. Atualmente, aprofundo a experiência com React e com a criação de produtos digitais.',
      ],
      principlesLabel: 'Princípios',
      principles: [
        ['Clareza', 'Soluções e comunicação devem ser fáceis de compreender.'],
        ['Curiosidade', 'Perguntar e investigar é parte essencial do trabalho.'],
        ['Consistência', 'Qualidade nasce de boas decisões repetidas diariamente.'],
      ],
      goalsLabel: 'Objetivos',
      goalsTitle: 'O próximo capítulo',
      goals:
        'Quero continuar a evoluir como desenvolvedor, colaborar com equipas diversas e construir produtos que gerem impacto mensurável para pessoas e negócios.',
    },
    projects: {
      eyebrow: 'PORTFÓLIO DE ENGENHARIA',
      title: 'Sistemas construídos para resolver problemas reais',
      description:
        'Projetos de backend, cloud, automação e integração desenvolvidos a partir de desafios reais de negócio.',
      viewProject: 'Ver estudo de caso',
      backToProjects: 'Voltar aos projetos',
      challenge: 'Problema',
      solution: 'Solução',
      stack: 'Tecnologias',
      caseStudy: {
        businessContext: 'Contexto do negócio',
        architectureImage: 'Visão do sistema',
        architecture: 'Arquitetura',
        applicationFunctioning: 'Funcionamento da solução',
        aiPipeline: 'Pipeline de IA',
        agentArchitecture: 'Arquitetura do agente',
        processingPipeline: 'Pipeline de processamento',
        processFlow: 'Fluxo do processo',
        executionCycle: 'Ciclo de execução',
        reliabilityRecovery: 'Confiabilidade e reprocessamento',
        recoveryPath: 'Caminho de recuperação',
        applicationArchitecture: 'Arquitetura da aplicação',
        productJourney: 'Jornada do produto',
        externalServices: 'Serviços externos',
        responsibility: 'Minha responsabilidade',
        requestFlow: 'Fluxo da requisição',
        decisions: 'Decisões arquiteturais',
        challenges: 'Principais desafios',
        results: 'Resultado',
        skills: 'Competências demonstradas',
      },
      items: [
        {
          slug: 'salesforce-serverless-integration',
          title: 'Integração Salesforce',
          summary: 'Integração distribuída entre Salesforce e serviços AWS utilizando arquitetura serverless e orientada a eventos.',
          challenge: 'Integrar sistemas independentes de forma confiável, reduzindo trabalho manual e garantindo consistência entre as informações.',
          solution: 'Fluxos de integração que mantêm os dados sincronizados e rastreáveis.',
          stack: ['Python', 'Lambda', 'API Gateway', 'SQS', 'Docker', 'Event-Driven'],
          imageAlt: 'Arquitetura serverless da integração Salesforce com serviços AWS',
          caseStudy: {
            businessContext: 'As informações necessárias para o processo comercial estavam distribuídas entre o Salesforce e serviços externos, exigindo uma integração confiável para sincronizar dados e reduzir atividades manuais.',
            responsibility: 'Desenhei e implementei o fluxo de integração, defini o mapeamento dos dados e organizei o tratamento de falhas para tornar a sincronização observável e segura.',
            architecture: 'A solução desacopla a origem dos dados da camada de integração, permitindo que cada sistema evolua de forma independente enquanto aumenta a resiliência e a observabilidade do processo.',
            architectureNodes: [
              { name: 'External System', detail: 'Serviço externo de consulta', type: 'external' },
              { name: 'Dead Letter Queue (DLQ)', detail: 'Falhas do Amazon SQS', type: 'dlq' },
            ],
            requestFlow: [
              { name: 'Salesforce', description: 'O usuário inicia a solicitação de sincronização.' },
              { name: 'API Gateway', description: 'Recebe a requisição e disponibiliza o endpoint da integração.' },
              { name: 'Amazon SQS', description: 'Enfileira a mensagem para processamento assíncrono e resiliente.' },
              { name: 'AWS Lambda', description: 'Processa os dados, aplica as transformações e integra os sistemas.' },
              { name: 'Salesforce', description: 'Recebe e guarda o resultado processado.' },
            ],
            challenges: ['Conciliar modelos de dados diferentes', 'Evitar registros duplicados durante reprocessamentos', 'Rastrear falhas sem interromper todo o fluxo'],
            decisions: ['Centralizar transformações para evitar regras duplicadas entre sistemas.', 'Usar identificadores externos para garantir idempotência em reprocessamentos.', 'Registrar contexto da execução para facilitar auditoria e troubleshooting.'],
            result: 'O fluxo reduziu tarefas manuais, aumentou a consistência das informações comerciais e criou uma base mais confiável para evoluir novas integrações.',
            resultBenefits: ['Redução de trabalho manual', 'Maior desacoplamento entre sistemas', 'Melhor confiabilidade', 'Base preparada para novas integrações'],
            skills: ['Integração de sistemas', 'Design de APIs', 'Modelagem de dados', 'Observabilidade', 'Serverless Architecture', 'Event-Driven Architecture'],
          },
        },
        {
          slug: 'melita-ai-agent',
          title: 'Melita AI Agent',
          summary: 'Assistente de IA serverless desenvolvido em Python e AWS Lambda para processamento de mensagens, automação conversacional e geração de conteúdo para LinkedIn utilizando LLMs.',
          challenge: 'Construir uma aplicação capaz de processar mensagens de texto e áudio, preservar o contexto das conversas, integrar múltiplos serviços externos e executar todo o fluxo em uma arquitetura serverless na AWS.',
          solution: 'Um agente orientado por objetivos com instruções e contexto estruturados.',
          stack: ['Python', 'LangChain', 'Lambda', 'Docker', 'CI/CD', 'LLM Integration'],
          imageAlt: 'Fluxo de funcionamento do agente de inteligência artificial Melita',
          caseStudy: {
            businessContext: 'O objetivo foi desenvolver uma aplicação capaz de receber mensagens pelo Telegram, interpretar a intenção do utilizador e automatizar a criação de conteúdo para LinkedIn através de modelos de linguagem, mantendo uma arquitetura modular, escalável e preparada para evolução contínua.',
            responsibility: 'Fui responsável pelo desenho da arquitetura, implementação do backend em Python, integração com OpenAI, Telegram e LinkedIn, organização do fluxo de processamento, testes automatizados, pipeline de CI/CD e deploy da aplicação em ambiente serverless na AWS.',
            architecture: 'A aplicação recebe eventos enviados pelo Telegram, processa mensagens de texto ou áudio, recupera o contexto recente da conversa e encaminha uma solicitação estruturada ao agente baseado em LangChain. Após classificar a intenção, o fluxo responde diretamente ao utilizador ou gera texto e imagem para publicação automática no LinkedIn.',
            requestFlow: [
              { name: 'Telegram', description: 'Envia mensagens de texto ou áudio para a aplicação.',},
              { name: 'AWS Lambda', description: 'Recebe o webhook, interpreta a requisição e inicia o fluxo serverless.',},
              { name: 'Processing', description: 'Transcreve áudio quando necessário, recupera o contexto da conversa e prepara a entrada do agente.',},
              { name: 'AI Agent', description: 'Classifica a intenção do utilizador e coordena a geração da resposta.',},
              { name: 'OpenAI', description: 'Gera texto ou conteúdo estruturado conforme o tipo de solicitação.',},
              { name: 'Integrations', description: 'Envia a resposta ao Telegram ou publica automaticamente texto e imagem no LinkedIn.',},
            ],
            challenges: ['Integrar múltiplas APIs externas mantendo baixo acoplamento.', 'Preservar contexto conversacional com consumo controlado de tokens.', 'Executar todo o fluxo em arquitetura serverless mantendo baixa latência.'],
            decisions: ['Separação entre agente, casos de uso e integrações externas.', 'Utilização de imagens Docker para execução da AWS Lambda.', 'Isolamento dos clientes OpenAI, Telegram e LinkedIn para aumentar testabilidade e facilitar evolução.'],
            result: 'O projeto resultou em uma aplicação serverless executada na AWS capaz de processar mensagens, transcrever áudio, gerar conteúdo utilizando LLMs e automatizar publicações no LinkedIn. A arquitetura modular, os testes automatizados e o pipeline de CI/CD tornam a solução mais simples de evoluir, manter e expandir.',
            resultBenefits: ['Arquitetura modular e desacoplada', 'Automação completa do fluxo de conteúdo', 'Deploy automatizado na AWS', 'Base preparada para evolução e testes'],
            skills: ['Backend Engineering', 'Cloud Engineering (AWS)', 'Serverless Architecture', 'API Integration', 'CI/CD & Automated Testing', 'LLM Integration'],
          },
        },
        {
          slug: 'process-automation-platform',
          title: 'Plataforma de Automação de Processos',
          summary: 'Plataforma de automação de processos em cloud para integração de sistemas, processamento de dados e execução de workflows.',
          challenge: 'Processos repetitivos consumiam tempo e dificultavam a escalabilidade.',
          solution: 'Rotinas Python executadas na AWS para processar e distribuir dados.',
          stack: ['Python', 'Docker', 'EventBridge', 'Step Functions', 'RPA', 'Data Processing'],
          imageAlt: 'Arquitetura da plataforma de automação de processos em AWS',
          caseStudy: {
            businessContext: 'A operação reunia processos recorrentes de integração e tratamento de dados que exigiam execução manual, acompanhamento constante e capacidade de crescer conforme o volume de trabalho.',
            responsibility: 'Implementei as rotinas em Python, estruturei a execução na AWS e defini mecanismos de validação, logs e reprocessamento para operar o fluxo com segurança.',
            architecture: 'A arquitetura orientada a eventos recebe a solicitação, orquestra o workflow e executa tarefas de automação independentes, preservando o estado e o resultado de cada etapa.',
            requestFlow: [
              { name: 'Scheduler', description: 'Inicia a automação no horário ou evento configurado.' },
              { name: 'Workflow', description: 'Orquestra as etapas, mantém o estado e controla as falhas.' },
              { name: 'Python Worker', description: 'Executa o processamento e as regras de automação.' },
              { name: 'Target System', description: 'Recebe os dados processados ou a ação concluída.' },
            ],
            recoveryFlow: [
              { name: 'Retry', description: 'Repete automaticamente etapas afetadas por falhas temporárias.' },
              { name: 'Failure State', description: 'Registra o erro, o estado e o contexto da execução.' },
              { name: 'Reprocessing', description: 'Retoma o processamento de forma segura a partir do ponto controlado.' },
            ],
            reliability: 'Cada execução mantém estado, logs e resultado identificáveis. Falhas temporárias utilizam retentativas controladas; quando a recuperação automática não é possível, o fluxo preserva o contexto necessário para análise e reprocessamento seguro.',
            challenges: ['Processar volumes variáveis sem intervenção manual', 'Lidar com falhas temporárias de serviços externos', 'Manter cada execução rastreável'],
            decisions: ['Adotar processamento assíncrono orientado a eventos', 'Criar tarefas pequenas e com responsabilidade definida', 'Aplicar retentativas controladas e estados explícitos de falha'],
            result: 'A automação diminuiu o tempo dedicado a tarefas repetitivas e permitiu escalar o processamento de forma previsível, com maior visibilidade operacional.',
            resultBenefits: ['Menos tarefas repetitivas', 'Processamento escalável', 'Maior rastreabilidade', 'Recuperação controlada de falhas'],
            skills: ['Python', 'Workflow Orchestration', 'RPA', 'Data Processing', 'Event-Driven Architecture', 'Reliability Engineering'],
          },
        },
        {
          slug: 'italian-learning-saas',
          title: 'Plataforma SaaS de Ensino de Italiano',
          summary: 'Plataforma SaaS para ensino de idiomas com APIs, pagamentos, gamificação e recursos de Inteligência Artificial.',
          challenge: 'Organizar conteúdos de maneira clara, progressiva e motivadora.',
          solution: 'Uma plataforma centrada na experiência e evolução de cada estudante.',
          stack: ['PHP', 'JavaScript', 'Stripe', 'REST API', 'SaaS', 'AI Features'],
          imageAlt: 'Arquitetura da plataforma SaaS de ensino de italiano',
          caseStudy: {
            businessContext: 'A plataforma precisava reunir conteúdos, pagamentos e acompanhamento do progresso numa experiência digital capaz de manter os estudantes envolvidos e apoiar a evolução contínua do produto.',
            responsibility: 'Modelei a experiência de aprendizagem, desenvolvi a interface em JavaScript e estruturei o backend em PHP para organizar conteúdos, pagamentos e progresso dos estudantes.',
            architecture: 'O frontend consome uma API REST implementada em PHP, responsável pelas regras da plataforma e pela persistência em MySQL. Serviços externos complementam pagamentos e recursos inteligentes.',
            requestFlow: [
              { name: 'User', description: 'Inicia uma ação de aprendizagem, pagamento ou consulta de progresso.' },
              { name: 'Frontend', description: 'Recolhe a interação e envia a solicitação para a aplicação.' },
              { name: 'Backend', description: 'Valida os dados e executa as regras de negócio.' },
              { name: 'Database', description: 'Guarda e disponibiliza conteúdos, pagamentos e progresso.' },
            ],
            externalIntegrations: [
              { name: 'Stripe', description: 'Processa pagamentos e subscrições fora do núcleo da aplicação.' },
              { name: 'AI Service', description: 'Disponibiliza recursos inteligentes para apoiar a aprendizagem.' },
            ],
            userJourney: [
              { name: 'Conteúdo', description: 'O estudante acede a um módulo organizado de forma progressiva.' },
              { name: 'Prática', description: 'Realiza atividades para aplicar o conteúdo estudado.' },
              { name: 'Feedback', description: 'Recebe uma resposta clara sobre o desempenho da atividade.' },
              { name: 'Progresso', description: 'A plataforma atualiza a evolução e prepara o próximo passo.' },
            ],
            challenges: ['Organizar conteúdo sem sobrecarregar a interface', 'Manter uma experiência consistente em diferentes telas', 'Representar progresso de forma simples e motivadora'],
            decisions: ['Dividir o conteúdo em módulos pequenos e progressivos', 'Separar frontend e backend por uma API REST', 'Integrar pagamentos por meio do Stripe'],
            result: 'A plataforma consolidou uma experiência de estudo acessível e responsiva, preparada para receber novos conteúdos e recursos de acompanhamento.',
            resultBenefits: ['Experiência de estudo centralizada', 'Progresso mais visível', 'Pagamentos integrados', 'Base preparada para novos recursos'],
            skills: ['PHP e JavaScript', 'Design de APIs REST', 'Modelagem MySQL', 'Arquitetura SaaS', 'Payment Integration', 'Full-Stack Development'],
          },
        },
      ],
    },
    experience: [
      {
        role: 'Cargo',
        company: 'Empresa',
        period: 'Período',
        summary: 'Resumo da experiência profissional será adicionado posteriormente.',
      },
      {
        role: 'Cargo',
        company: 'Empresa',
        period: 'Período',
        summary: 'Resumo da experiência profissional será adicionado posteriormente.',
      },
    ],
    common: {
      featuredLink: 'Ver todos os projetos',
      email: 'Enviar e-mail',
      footer: 'Desenvolvido com React, TypeScript e atenção aos detalhes.',
      imageUnavailable: 'Imagem do projeto será adicionada em breve',
    },
  },
  en: {
    nav: { home: 'Home', about: 'About', projects: 'Projects' },
    home: {
      eyebrow: 'Software Engineer | Backend & Cloud',
      title: 'Engineering scalable backend systems',
      description:
        'I build APIs, integrations, and serverless architectures to create distributed systems running in production.',
      primaryAction: 'View projects',
      secondaryAction: 'Get in touch',
      specialtiesLabel: 'Expertise',
      specialtiesTitle: 'Technology applied to real problems',
      specialties: [
        {
          title: 'Backend Engineering',
          description: 'APIs and services built for clarity, reliability, and continuous evolution.',
          icon: 'backend',
        },
        {
          title: 'Cloud & AWS',
          description: 'Serverless architectures and automation designed to operate in the cloud.',
          icon: 'cloud',
        },
        {
          title: 'Distributed Systems & Integrations',
          description: 'Event-driven systems and integrations that create reliable workflows.',
          icon: 'systems',
        },
      ],
      featuredLabel: 'Featured projects',
      featuredTitle: 'A selection of my work',
      experienceLabel: 'Experience',
      experienceTitle: 'Continuous learning, practical delivery',
      experience:
        'My path combines development, automation, and systems integration. I seek to understand the context before choosing technology and value simple, sustainable solutions.',
      contactLabel: 'Contact',
      contactTitle: 'Shall we build something together?',
      contact: 'I am available to talk about projects, opportunities, and good ideas.',
    },
    about: {
      eyebrow: 'About me',
      title: 'Technology with curiosity, clarity, and purpose.',
      journeyLabel: 'Journey',
      journeyTitle: 'Building a complete perspective',
      journey: [
        'I am a developer interested in solving problems through technology. I enjoy understanding how every part of a system connects and how software can make people’s work easier.',
        'My path combines Python, cloud, integrations, and web development. I am currently deepening my experience with React and digital product development.',
      ],
      principlesLabel: 'Principles',
      principles: [
        ['Clarity', 'Solutions and communication should be easy to understand.'],
        ['Curiosity', 'Asking questions and investigating are essential parts of the work.'],
        ['Consistency', 'Quality comes from good decisions repeated every day.'],
      ],
      goalsLabel: 'Goals',
      goalsTitle: 'The next chapter',
      goals:
        'I want to keep growing as a developer, collaborate with diverse teams, and build products that create measurable impact for people and businesses.',
    },
    projects: {
      eyebrow: 'ENGINEERING PORTFOLIO',
      title: 'Building Systems That Solve Real Business Problems',
      description:
        'Backend, cloud, automation, and integration projects designed to solve real business challenges.',
      viewProject: 'View case study',
      backToProjects: 'Back to projects',
      challenge: 'Problem',
      solution: 'Solution',
      stack: 'Technologies',
      caseStudy: {
        businessContext: 'Business context',
        architectureImage: 'System overview',
        architecture: 'Architecture',
        applicationFunctioning: 'How the application works',
        aiPipeline: 'AI pipeline',
        agentArchitecture: 'Agent architecture',
        processingPipeline: 'Processing pipeline',
        processFlow: 'Process flow',
        executionCycle: 'Execution cycle',
        reliabilityRecovery: 'Reliability and reprocessing',
        recoveryPath: 'Recovery path',
        applicationArchitecture: 'Application architecture',
        productJourney: 'Product journey',
        externalServices: 'External services',
        responsibility: 'My responsibility',
        requestFlow: 'Request flow',
        decisions: 'Architectural decisions',
        challenges: 'Key challenges',
        results: 'Outcome',
        skills: 'Skills demonstrated',
      },
      items: [
        {
          slug: 'salesforce-serverless-integration',
          title: 'Salesforce Integration',
          summary: 'Distributed integration between Salesforce and AWS services using a serverless, event-driven architecture.',
          challenge: 'Unify distributed information and reduce manual tasks across systems.',
          solution: 'Integration workflows that keep data synchronized and traceable.',
          stack: ['Python', 'Lambda', 'API Gateway', 'SQS', 'Docker', 'Event-Driven'],
          imageAlt: 'Serverless architecture for the Salesforce integration with AWS services',
          caseStudy: {
            businessContext: 'The commercial operation depended on information distributed between Salesforce and external services, making data synchronization essential for reliable processes and reduced manual work.',
            responsibility: 'I designed and implemented the integration flow, defined data mappings, and organized failure handling to make synchronization observable and reliable.',
            architecture: 'The solution separates the data source, integration layer, and Salesforce. API communication keeps systems decoupled, while validation and execution records make every operation easier to trace.',
            architectureNodes: [
              { name: 'External System', detail: 'External lookup service', type: 'external' },
              { name: 'Dead Letter Queue (DLQ)', detail: 'Amazon SQS failures', type: 'dlq' },
            ],
            requestFlow: [
              { name: 'Salesforce', description: 'The user initiates the synchronization request.' },
              { name: 'API Gateway', description: 'Receives the request and exposes the integration endpoint.' },
              { name: 'Amazon SQS', description: 'Queues the message for asynchronous and resilient processing.' },
              { name: 'AWS Lambda', description: 'Processes the data, applies transformations, and integrates the systems.' },
              { name: 'Salesforce', description: 'Receives and stores the processed result.' },
            ],
            challenges: ['Reconcile different data models', 'Prevent duplicate records during reprocessing', 'Trace failures without stopping the entire flow'],
            decisions: ['Centralize transformations in the integration layer', 'Use external identifiers to guarantee idempotency', 'Record the context and outcome of each synchronization'],
            result: 'The flow reduced manual work, improved commercial data consistency, and established a reliable foundation for additional integrations.',
            resultBenefits: ['Reduced manual work', 'Greater system decoupling', 'Improved reliability', 'Foundation for new integrations'],
            skills: ['Systems integration', 'API design', 'Data modeling', 'Observability', 'Serverless Architecture', 'Event-Driven Architecture'],
          },
        },
        {
          slug: 'melita-ai-agent',
          title: 'Melita AI Agent',
          summary: 'Serverless AI assistant built with Python and AWS Lambda for message processing, conversational automation, and LinkedIn content generation using LLMs.',
          challenge: 'Build an application capable of processing text and audio messages, preserving conversation context, integrating multiple external services, and running the entire workflow on a serverless AWS architecture.',
          solution: 'A goal-oriented agent with structured instructions and context.',
          stack: ['Python', 'LangChain', 'Lambda', 'Docker', 'CI/CD', 'LLM Integration'],
          imageAlt: 'Workflow of the Melita artificial intelligence agent',
          caseStudy: {
            businessContext: 'The goal was to develop an application capable of receiving messages through Telegram, interpreting the user’s intent, and automating LinkedIn content creation with language models while maintaining a modular, scalable architecture prepared for continuous evolution.',
            responsibility: 'I was responsible for the architecture design, Python backend implementation, OpenAI, Telegram, and LinkedIn integrations, processing workflow organization, automated tests, CI/CD pipeline, and deployment of the application in a serverless AWS environment.',
            architecture: 'The application receives events sent by Telegram, processes text or audio messages, retrieves the recent conversation context, and forwards a structured request to the LangChain-based agent. After classifying the intent, the workflow either responds directly to the user or generates text and an image for automatic publication on LinkedIn.',
            requestFlow: [
              { name: 'Telegram', description: 'Sends text or audio messages to the application.' },
              { name: 'AWS Lambda', description: 'Receives the webhook, interprets the request, and starts the serverless workflow.' },
              { name: 'Processing', description: 'Transcribes audio when necessary, retrieves the conversation context, and prepares the agent input.' },
              { name: 'AI Agent', description: 'Classifies the user’s intent and coordinates response generation.' },
              { name: 'OpenAI', description: 'Generates text or structured content according to the request type.' },
              { name: 'Integrations', description: 'Sends the response to Telegram or automatically publishes text and an image on LinkedIn.' },
            ],
            challenges: ['Integrate multiple external APIs while maintaining low coupling.', 'Preserve conversational context with controlled token consumption.', 'Run the entire workflow on a serverless architecture while maintaining low latency.'],
            decisions: ['Separate the agent, use cases, and external integrations.', 'Use Docker images to run the AWS Lambda function.', 'Isolate the OpenAI, Telegram, and LinkedIn clients to improve testability and simplify future evolution.'],
            result: 'The project resulted in a serverless application running on AWS that can process messages, transcribe audio, generate content using LLMs, and automate LinkedIn posts. Its modular architecture, automated tests, and CI/CD pipeline make the solution easier to evolve, maintain, and expand.',
            resultBenefits: ['Modular and decoupled architecture', 'Complete content workflow automation', 'Automated deployment on AWS', 'Foundation prepared for evolution and testing'],
            skills: ['Backend Engineering', 'Cloud Engineering (AWS)', 'Serverless Architecture', 'API Integration', 'CI/CD & Automated Testing', 'LLM Integration'],
          },
        },
        {
          slug: 'process-automation-platform',
          title: 'Process Automation Platform',
          summary: 'Cloud process automation platform for system integration, data processing, and workflow execution.',
          challenge: 'Repetitive processes consumed time and made scaling difficult.',
          solution: 'Python routines running on AWS to process and distribute data.',
          stack: ['Python', 'Docker', 'EventBridge', 'Step Functions', 'RPA', 'Data Processing'],
          imageAlt: 'Architecture of the process automation platform on AWS',
          caseStudy: {
            businessContext: 'The operation involved recurring integration and data-processing workflows that required manual execution, constant monitoring, and the ability to scale with demand.',
            responsibility: 'I implemented the Python routines, structured execution on AWS, and defined validation, logging, and reprocessing mechanisms for reliable operation.',
            architecture: 'The event-driven architecture receives a request, orchestrates the workflow, and executes independent automation tasks with traceable state and outcomes.',
            requestFlow: [
              { name: 'Scheduler', description: 'Starts the automation at the configured time or event.' },
              { name: 'Workflow', description: 'Orchestrates the steps, preserves state, and controls failures.' },
              { name: 'Python Worker', description: 'Executes the processing and automation rules.' },
              { name: 'Target System', description: 'Receives the processed data or completed action.' },
            ],
            recoveryFlow: [
              { name: 'Retry', description: 'Automatically repeats steps affected by temporary failures.' },
              { name: 'Failure State', description: 'Records the error, state, and execution context.' },
              { name: 'Reprocessing', description: 'Safely resumes processing from a controlled point.' },
            ],
            reliability: 'Each execution preserves identifiable state, logs, and outcomes. Temporary failures use controlled retries; when automatic recovery is not possible, the workflow retains the context required for analysis and safe reprocessing.',
            challenges: ['Process variable workloads without manual intervention', 'Handle temporary failures in external services', 'Keep every execution traceable'],
            decisions: ['Use asynchronous event-based processing', 'Create small tasks with focused responsibilities', 'Apply controlled retries and explicit failure states'],
            result: 'The automation reduced time spent on repetitive tasks and enabled predictable processing at scale with improved operational visibility.',
            resultBenefits: ['Fewer repetitive tasks', 'Scalable processing', 'Greater traceability', 'Controlled failure recovery'],
            skills: ['Python', 'Workflow Orchestration', 'RPA', 'Data Processing', 'Event-Driven Architecture', 'Reliability Engineering'],
          },
        },
        {
          slug: 'italian-learning-saas',
          title: 'Italian Learning SaaS Platform',
          summary: 'Language learning SaaS platform with APIs, payments, gamification, and artificial intelligence features.',
          challenge: 'Organize content in a clear, progressive, and motivating way.',
          solution: 'A platform centered on each student’s experience and progress.',
          stack: ['PHP', 'JavaScript', 'Stripe', 'REST API', 'SaaS', 'AI Features'],
          imageAlt: 'Architecture of the Italian learning SaaS platform',
          caseStudy: {
            businessContext: 'The platform needed to combine content, payments, and progress tracking in a digital experience that could keep students engaged and support the product’s continuous evolution.',
            responsibility: 'I modeled the learning experience, developed the JavaScript interface, and structured the PHP backend for content, payments, and student progress.',
            architecture: 'The frontend consumes a REST API implemented in PHP, which handles platform rules and MySQL persistence. External services support payments and intelligent features.',
            requestFlow: [
              { name: 'User', description: 'Starts a learning, payment, or progress-tracking action.' },
              { name: 'Frontend', description: 'Captures the interaction and sends the request to the application.' },
              { name: 'Backend', description: 'Validates the data and executes the business rules.' },
              { name: 'Database', description: 'Stores and provides content, payments, and progress data.' },
            ],
            externalIntegrations: [
              { name: 'Stripe', description: 'Processes payments and subscriptions outside the application core.' },
              { name: 'AI Service', description: 'Provides intelligent features that support the learning experience.' },
            ],
            userJourney: [
              { name: 'Content', description: 'The student accesses a module organized as a progressive learning step.' },
              { name: 'Practice', description: 'Completes activities to apply the studied content.' },
              { name: 'Feedback', description: 'Receives a clear response about the activity performance.' },
              { name: 'Progress', description: 'The platform updates progress and prepares the next step.' },
            ],
            challenges: ['Organize content without overwhelming the interface', 'Keep the experience consistent across screen sizes', 'Represent progress in a simple and motivating way'],
            decisions: ['Split content into small progressive modules', 'Separate frontend and backend through a REST API', 'Integrate payments through Stripe'],
            result: 'The platform established an accessible, responsive study experience ready to receive new content and progress-tracking features.',
            resultBenefits: ['Centralized study experience', 'Clearer progress tracking', 'Integrated payments', 'Foundation for new features'],
            skills: ['PHP and JavaScript', 'REST API design', 'MySQL modeling', 'SaaS architecture', 'Payment Integration', 'Full-Stack Development'],
          },
        },
      ],
    },
    experience: [
      {
        role: 'Role',
        company: 'Company',
        period: 'Period',
        summary: 'The professional experience summary will be added later.',
      },
      {
        role: 'Role',
        company: 'Company',
        period: 'Period',
        summary: 'The professional experience summary will be added later.',
      },
    ],
    common: {
      featuredLink: 'View all projects',
      email: 'Send an email',
      footer: 'Built with React, TypeScript and attention to detail.',
      imageUnavailable: 'Project image coming soon',
    },
  },
}
