import type { Language, SiteContent } from './types'

export const content: Record<Language, SiteContent> = {
  pt: {
    nav: { home: 'Home', about: 'Sobre', projects: 'Projetos' },
    home: {
      eyebrow: 'Software Engineer | Backend & Cloud',
      title: 'Engenharia de sistemas backend escaláveis.',
      description:
        'Desenvolvo APIs, integrações e arquiteturas serverless com Python e AWS para criar sistemas distribuídos executados em produção.',
      primaryAction: 'Ver projetos',
      secondaryAction: 'Entrar em contato',
      specialtiesLabel: 'Especialidades',
      specialtiesTitle: 'Tecnologia aplicada a problemas reais',
      specialties: [
        {
          title: 'Backend Engineering',
          description: 'APIs e serviços criados com clareza, confiabilidade e capacidade de evolução.',
          icon: 'backend',
        },
        {
          title: 'Cloud & AWS',
          description: 'Arquiteturas serverless e automações preparadas para operar em nuvem.',
          icon: 'cloud',
        },
        {
          title: 'Distributed Systems & Integrations',
          description: 'Sistemas orientados a eventos e integrações para criar fluxos confiáveis.',
          icon: 'systems',
        },
      ],
      featuredLabel: 'Projetos em destaque',
      featuredTitle: 'Uma seleção do meu trabalho',
      experienceLabel: 'Experiência resumida',
      experienceTitle: 'Aprendizado contínuo, entrega prática',
      experience:
        'Minha trajetória combina desenvolvimento, automação e integração de sistemas. Procuro compreender o contexto antes de escolher a tecnologia e valorizo soluções simples e sustentáveis.',
      contactLabel: 'Contato',
      contactTitle: 'Vamos construir algo juntos?',
      contact:
        'Estou disponível para conversar sobre projetos, oportunidades e boas ideias.',
    },
    projects: {
      eyebrow: 'Portfólio de projetos',
      title: 'Projetos construídos para resolver problemas reais.',
      description:
        'Cada projeto parte de um contexto diferente, mas segue o mesmo princípio: usar tecnologia com propósito e clareza.',
      viewProject: 'Ver estudo de caso',
      backToProjects: 'Voltar aos projetos',
      challenge: 'Problema',
      solution: 'Solução',
      stack: 'Tecnologias',
      caseStudy: {
        architecture: 'Arquitetura',
        responsibilities: 'Responsabilidades',
        decisions: 'Decisões técnicas',
        challenges: 'Desafios',
        results: 'Resultados',
        evidence: 'Galeria de evidências',
        links: 'Links externos',
        placeholder: 'Conteúdo será adicionado após a documentação do projeto.',
      },
      items: [
        {
          slug: 'salesforce-integration',
          number: '01',
          title: 'Integração Salesforce',
          summary: 'Integração de dados e processos para uma operação comercial mais eficiente.',
          challenge: 'Unificar informações distribuídas e diminuir tarefas manuais entre sistemas.',
          solution: 'Fluxos de integração que mantêm os dados sincronizados e rastreáveis.',
          stack: ['Salesforce', 'APIs', 'Integração'],
          imageAlt: 'Diagrama do projeto de integração Salesforce',
        },
        {
          slug: 'python-aws-automation',
          number: '02',
          title: 'Automação Python + AWS',
          summary: 'Automação de tarefas e processamento de dados usando serviços em nuvem.',
          challenge: 'Processos repetitivos consumiam tempo e dificultavam a escalabilidade.',
          solution: 'Rotinas Python executadas na AWS para processar e distribuir dados.',
          stack: ['Python', 'AWS', 'Automação'],
          imageAlt: 'Arquitetura da automação construída com Python e AWS',
        },
        {
          slug: 'melita-ai-agent',
          number: '03',
          title: 'Melita AI Agent',
          summary: 'Agente de IA criado para apoiar conversas e decisões.',
          challenge: 'Oferecer respostas úteis sem perder o contexto da conversa.',
          solution: 'Um agente orientado por objetivos com instruções e contexto estruturados.',
          stack: ['IA', 'Agentes', 'Produto'],
          imageAlt: 'Fluxo de funcionamento do agente de inteligência artificial Melita',
        },
        {
          slug: 'italian-learning-platform',
          number: '04',
          title: 'Plataforma de ensino de italiano',
          summary: 'Experiência digital para tornar o aprendizado mais acessível.',
          challenge: 'Organizar conteúdos de maneira clara, progressiva e motivadora.',
          solution: 'Uma plataforma centrada na experiência e evolução de cada estudante.',
          stack: ['Educação', 'React', 'UX'],
          imageAlt: 'Interface da plataforma de ensino de italiano',
        },
      ],
    },
    experience: [
      {
        role: 'Cargo',
        company: 'Empresa',
        period: 'Período',
        summary: 'Resumo da experiência profissional será adicionado posteriormente.',
      },
      {
        role: 'Cargo',
        company: 'Empresa',
        period: 'Período',
        summary: 'Resumo da experiência profissional será adicionado posteriormente.',
      },
    ],
    about: {
      eyebrow: 'Sobre mim',
      title: 'Tecnologia com curiosidade, clareza e propósito.',
      journeyLabel: 'Trajetória',
      journeyTitle: 'Construindo uma visão completa',
      journey: [
        'Sou um desenvolvedor interessado em resolver problemas por meio da tecnologia. Gosto de compreender como cada parte de um sistema se conecta e como o software pode facilitar o trabalho das pessoas.',
        'A minha trajetória combina Python, cloud, integrações e desenvolvimento web. Atualmente, aprofundo a experiência com React e com a criação de produtos digitais.',
      ],
      principlesLabel: 'Princípios',
      principles: [
        ['Clareza', 'Soluções e comunicação devem ser fáceis de compreender.'],
        ['Curiosidade', 'Perguntar e investigar é parte essencial do trabalho.'],
        ['Consistência', 'Qualidade nasce de boas decisões repetidas diariamente.'],
      ],
      goalsLabel: 'Objetivos',
      goalsTitle: 'O próximo capítulo',
      goals:
        'Quero continuar a evoluir como desenvolvedor, colaborar com equipas diversas e construir produtos que gerem impacto mensurável para pessoas e negócios.',
    },
    common: {
      featuredLink: 'Ver todos os projetos',
      email: 'Enviar e-mail',
      footer: 'Desenvolvido com React e curiosidade.',
      imageUnavailable: 'Imagem do projeto será adicionada em breve',
    },
  },
  en: {
    nav: { home: 'Home', about: 'About', projects: 'Projects' },
    home: {
      eyebrow: 'Software Engineer | Backend & Cloud',
      title: 'Engineering scalable backend systems.',
      description:
        'I build APIs, integrations, and serverless architectures with Python and AWS, delivering distributed systems for production environments.',
      primaryAction: 'View projects',
      secondaryAction: 'Get in touch',
      specialtiesLabel: 'Expertise',
      specialtiesTitle: 'Technology applied to real problems',
      specialties: [
        {
          title: 'Backend Engineering',
          description: 'APIs and services built for clarity, reliability, and continuous evolution.',
          icon: 'backend',
        },
        {
          title: 'Cloud & AWS',
          description: 'Serverless architectures and automation designed to operate in the cloud.',
          icon: 'cloud',
        },
        {
          title: 'Distributed Systems & Integrations',
          description: 'Event-driven systems and integrations that create reliable workflows.',
          icon: 'systems',
        },
      ],
      featuredLabel: 'Featured projects',
      featuredTitle: 'A selection of my work',
      experienceLabel: 'Experience',
      experienceTitle: 'Continuous learning, practical delivery',
      experience:
        'My path combines development, automation, and systems integration. I seek to understand the context before choosing technology and value simple, sustainable solutions.',
      contactLabel: 'Contact',
      contactTitle: 'Shall we build something together?',
      contact: 'I am available to talk about projects, opportunities, and good ideas.',
    },
    projects: {
      eyebrow: 'Project portfolio',
      title: 'Projects built to solve real problems.',
      description:
        'Each project starts from a different context but follows the same principle: using technology with purpose and clarity.',
      viewProject: 'View case study',
      backToProjects: 'Back to projects',
      challenge: 'Problem',
      solution: 'Solution',
      stack: 'Technologies',
      caseStudy: {
        architecture: 'Architecture',
        responsibilities: 'Responsibilities',
        decisions: 'Technical decisions',
        challenges: 'Challenges',
        results: 'Results',
        evidence: 'Evidence gallery',
        links: 'External links',
        placeholder: 'Content will be added after the project is documented.',
      },
      items: [
        {
          slug: 'salesforce-integration',
          number: '01',
          title: 'Salesforce Integration',
          summary: 'Data and process integration for more efficient commercial operations.',
          challenge: 'Unify distributed information and reduce manual tasks across systems.',
          solution: 'Integration workflows that keep data synchronized and traceable.',
          stack: ['Salesforce', 'APIs', 'Integration'],
          imageAlt: 'Diagram of the Salesforce integration project',
        },
        {
          slug: 'python-aws-automation',
          number: '02',
          title: 'Python + AWS Automation',
          summary: 'Task automation and data processing using cloud services.',
          challenge: 'Repetitive processes consumed time and made scaling difficult.',
          solution: 'Python routines running on AWS to process and distribute data.',
          stack: ['Python', 'AWS', 'Automation'],
          imageAlt: 'Architecture of the automation built with Python and AWS',
        },
        {
          slug: 'melita-ai-agent',
          number: '03',
          title: 'Melita AI Agent',
          summary: 'An AI agent designed to support conversations and decisions.',
          challenge: 'Provide useful answers without losing conversation context.',
          solution: 'A goal-oriented agent with structured instructions and context.',
          stack: ['AI', 'Agents', 'Product'],
          imageAlt: 'Workflow of the Melita artificial intelligence agent',
        },
        {
          slug: 'italian-learning-platform',
          number: '04',
          title: 'Italian learning platform',
          summary: 'A digital experience designed to make learning more accessible.',
          challenge: 'Organize content in a clear, progressive, and motivating way.',
          solution: 'A platform centered on each student’s experience and progress.',
          stack: ['Education', 'React', 'UX'],
          imageAlt: 'Interface of the Italian learning platform',
        },
      ],
    },
    experience: [
      {
        role: 'Role',
        company: 'Company',
        period: 'Period',
        summary: 'The professional experience summary will be added later.',
      },
      {
        role: 'Role',
        company: 'Company',
        period: 'Period',
        summary: 'The professional experience summary will be added later.',
      },
    ],
    about: {
      eyebrow: 'About me',
      title: 'Technology with curiosity, clarity, and purpose.',
      journeyLabel: 'Journey',
      journeyTitle: 'Building a complete perspective',
      journey: [
        'I am a developer interested in solving problems through technology. I enjoy understanding how every part of a system connects and how software can make people’s work easier.',
        'My path combines Python, cloud, integrations, and web development. I am currently deepening my experience with React and digital product development.',
      ],
      principlesLabel: 'Principles',
      principles: [
        ['Clarity', 'Solutions and communication should be easy to understand.'],
        ['Curiosity', 'Asking questions and investigating are essential parts of the work.'],
        ['Consistency', 'Quality comes from good decisions repeated every day.'],
      ],
      goalsLabel: 'Goals',
      goalsTitle: 'The next chapter',
      goals:
        'I want to keep growing as a developer, collaborate with diverse teams, and build products that create measurable impact for people and businesses.',
    },
    common: {
      featuredLink: 'View all projects',
      email: 'Send an email',
      footer: 'Built with React and curiosity.',
      imageUnavailable: 'Project image coming soon',
    },
  },
}
