import type { Language, SiteContent } from './types'

export const content: Record<Language, SiteContent> = {
  pt: {
    nav: { home: 'Home', about: 'Sobre', projects: 'Projetos' },
    home: {
      eyebrow: 'Software Engineer | Backend & Cloud',
      title: 'Engenharia de sistemas backend escaláveis',
      description:
        'Desenvolvo APIs, integrações e arquiteturas serverless para criar sistemas distribuídos executados em produção.',
      primaryAction: 'Ver projetos',
      secondaryAction: 'Entrar em contato',
      specialtiesLabel: 'Especialidades',
      specialtiesTitle: 'Tecnologia aplicada a problemas reais',
      specialties: [
        {
          title: 'Backend Engineering',
          description: 'APIs e serviços criados com clareza, confiabilidade e capacidade de evolução.',
          icon: 'backend',
        },
        {
          title: 'Cloud & AWS',
          description: 'Arquiteturas serverless e automações preparadas para operar em nuvem.',
          icon: 'cloud',
        },
        {
          title: 'Distributed Systems & Integrations',
          description: 'Sistemas orientados a eventos e integrações para criar fluxos confiáveis.',
          icon: 'systems',
        },
      ],
      featuredLabel: 'Projetos em destaque',
      featuredTitle: 'Uma seleção do meu trabalho',
      experienceLabel: 'Experiência resumida',
      experienceTitle: 'Aprendizado contínuo, entrega prática',
      experience:
        'Minha trajetória combina desenvolvimento, automação e integração de sistemas. Procuro compreender o contexto antes de escolher a tecnologia e valorizo soluções simples e sustentáveis.',
      contactLabel: 'Contato',
      contactTitle: 'Vamos construir algo juntos?',
      contact:
        'Estou disponível para conversar sobre projetos, oportunidades e boas ideias.',
    },
    about: {
      eyebrow: 'Sobre mim',
      title: 'Tecnologia com curiosidade, clareza e propósito.',
      journeyLabel: 'Trajetória',
      journeyTitle: 'Construindo uma visão completa',
      journey: [
        'Sou um desenvolvedor interessado em resolver problemas por meio da tecnologia. Gosto de compreender como cada parte de um sistema se conecta e como o software pode facilitar o trabalho das pessoas.',
        'A minha trajetória combina Python, cloud, integrações e desenvolvimento web. Atualmente, aprofundo a experiência com React e com a criação de produtos digitais.',
      ],
      principlesLabel: 'Princípios',
      principles: [
        ['Clareza', 'Soluções e comunicação devem ser fáceis de compreender.'],
        ['Curiosidade', 'Perguntar e investigar é parte essencial do trabalho.'],
        ['Consistência', 'Qualidade nasce de boas decisões repetidas diariamente.'],
      ],
      goalsLabel: 'Objetivos',
      goalsTitle: 'O próximo capítulo',
      goals:
        'Quero continuar a evoluir como desenvolvedor, colaborar com equipas diversas e construir produtos que gerem impacto mensurável para pessoas e negócios.',
    },
    projects: {
      eyebrow: 'PORTFÓLIO DE ENGENHARIA',
      title: 'Sistemas construídos para resolver problemas reais',
      description:
        'Projetos de backend, cloud, automação e integração desenvolvidos a partir de desafios reais de negócio.',
      viewProject: 'Ver estudo de caso',
      backToProjects: 'Voltar aos projetos',
      challenge: 'Problema',
      solution: 'Solução',
      stack: 'Tecnologias',
      caseStudy: {
        architectureImage: 'Visão do sistema',
        architecture: 'Arquitetura',
        responsibility: 'Minha responsabilidade',
        requestFlow: 'Fluxo da requisição',
        decisions: 'Decisões técnicas',
        challenges: 'Principais desafios',
        results: 'Resultado',
        skills: 'Competências demonstradas',
      },
      items: [
        {
          slug: 'salesforce-integration',
          number: '01',
          title: 'Integração Salesforce',
          summary: 'Integração distribuída entre Salesforce e serviços AWS utilizando arquitetura serverless e orientada a eventos.',
          challenge: 'Unificar informações distribuídas e diminuir tarefas manuais entre sistemas.',
          solution: 'Fluxos de integração que mantêm os dados sincronizados e rastreáveis.',
          stack: ['Python', 'AWS', 'Lambda','API Gateway', 'Amazon SQS', 'Docker'],
          imageAlt: 'Diagrama do projeto de integração Salesforce',
          caseStudy: {
            responsibility: 'Desenhei e implementei o fluxo de integração, defini o mapeamento dos dados e organizei o tratamento de falhas para tornar a sincronização observável e segura.',
            architecture: 'A solução separa a origem dos dados, a camada de integração e o Salesforce. A comunicação por APIs mantém os sistemas desacoplados, enquanto validações e registros de execução facilitam o acompanhamento de cada operação.',
            requestFlow: ['Sistema de origem', 'API Gateway', 'Amazon SQS', 'Salesforce'],
            challenges: ['Conciliar modelos de dados diferentes', 'Evitar registros duplicados durante reprocessamentos', 'Rastrear falhas sem interromper todo o fluxo'],
            decisions: ['Centralizar transformações na camada de integração', 'Usar identificadores externos para garantir idempotência', 'Registrar contexto e resultado de cada sincronização'],
            result: 'O fluxo reduziu tarefas manuais, aumentou a consistência das informações comerciais e criou uma base mais confiável para evoluir novas integrações.',
            skills: ['Integração de sistemas', 'Design de APIs', 'Modelagem de dados', 'Observabilidade'],
          },
        },
        {
          slug: 'melita-ai-agent',
          number: '02',
          title: 'Melita AI Agent',
          summary: 'Agente de IA serverless com LangChain e AWS Lambda para processamento de linguagem natural e integração com LLMs.',
          challenge: 'Oferecer respostas úteis sem perder o contexto da conversa.',
          solution: 'Um agente orientado por objetivos com instruções e contexto estruturados.',
          stack: ['Python', 'LangChain', 'AWS Lambda', 'Docker', 'GitHub Actions', 'LLMs'],
          imageAlt: 'Fluxo de funcionamento do agente de inteligência artificial Melita',
          caseStudy: {
            responsibility: 'Estruturei o comportamento do agente, organizei as fontes de contexto e implementei o fluxo de conversa, incluindo validações para respostas mais consistentes.',
            architecture: 'A aplicação recebe a mensagem, recupera o contexto relevante e monta uma solicitação estruturada para o modelo. A resposta passa por validação antes de retornar à interface e atualizar o histórico.',
            requestFlow: ['Usuário', 'AWS Lambda', 'LangChain', 'LLM'],
            challenges: ['Preservar contexto sem aumentar ruído na conversa', 'Reduzir respostas imprecisas ou fora do objetivo', 'Equilibrar qualidade, latência e custo'],
            decisions: ['Separar instruções, memória e mensagem do usuário', 'Limitar o contexto ao conteúdo relevante', 'Validar a saída antes de apresentá-la na interface'],
            result: 'O agente passou a produzir interações mais contextualizadas e previsíveis, criando uma base clara para testes, avaliação e evolução do produto.',
            skills: ['Engenharia de prompts', 'Agentes de IA', 'Arquitetura de contexto', 'Desenvolvimento de produto'],
          },
        },
        {
          slug: 'python-aws-automation',
          number: '03',
          title: 'Plataforma de Automação de Processos',
          summary: 'Plataforma de automação de processos em cloud para integração de sistemas, processamento de dados e execução de workflows.',
          challenge: 'Processos repetitivos consumiam tempo e dificultavam a escalabilidade.',
          solution: 'Rotinas Python executadas na AWS para processar e distribuir dados.',
          stack: ['Python', 'AWS', 'Docker', 'EventBridge', 'RPA','Step Functions'],
          imageAlt: 'Arquitetura da automação construída com Python e AWS',
          caseStudy: {
            responsibility: 'Implementei as rotinas em Python, estruturei a execução na AWS e defini mecanismos de validação, logs e reprocessamento para operar o fluxo com segurança.',
            architecture: 'A arquitetura orientada a eventos recebe a solicitação, distribui o trabalho por uma fila e executa funções independentes. O armazenamento preserva entradas e resultados para auditoria e reprocessamento.',
            requestFlow: ['Evento', 'Step Functions', 'Automação Python', 'Sistema externo'],
            challenges: ['Processar volumes variáveis sem intervenção manual', 'Lidar com falhas temporárias de serviços externos', 'Manter cada execução rastreável'],
            decisions: ['Adotar processamento assíncrono com filas', 'Criar funções pequenas e com responsabilidade definida', 'Aplicar retentativas controladas e fila de mensagens com erro'],
            result: 'A automação diminuiu o tempo dedicado a tarefas repetitivas e permitiu escalar o processamento de forma previsível, com maior visibilidade operacional.',
            skills: ['Python', 'AWS Serverless', 'Sistemas orientados a eventos', 'Automação'],
          },
        },
        {
          slug: 'italian-learning-platform',
          number: '04',
          title: 'Plataforma SaaS de Ensino de Italiano',
          summary: 'Plataforma SaaS para ensino de idiomas com APIs, pagamentos, gamificação e recursos de Inteligência Artificial.',
          challenge: 'Organizar conteúdos de maneira clara, progressiva e motivadora.',
          solution: 'Uma plataforma centrada na experiência e evolução de cada estudante.',
          stack: ['PHP', 'JavaScript', 'MySQL', 'REST API', 'SaaS', 'Stripe'],
          imageAlt: 'Interface da plataforma de ensino de italiano',
          caseStudy: {
            responsibility: 'Modelei a experiência de aprendizagem, desenvolvi a interface em React e organizei a estrutura de conteúdos e progresso para apoiar uma evolução gradual.',
            architecture: 'A interface React consome uma camada de conteúdo organizada por módulos. O estado da aplicação acompanha a navegação e o progresso, permitindo evoluir futuramente para persistência em uma API.',
            requestFlow: ['Frontend', 'REST API', 'Backend', 'MySQL'],
            challenges: ['Organizar conteúdo sem sobrecarregar a interface', 'Manter uma experiência consistente em diferentes telas', 'Representar progresso de forma simples e motivadora'],
            decisions: ['Dividir o conteúdo em módulos pequenos e progressivos', 'Criar componentes reutilizáveis para lições e exercícios', 'Priorizar navegação clara e feedback imediato'],
            result: 'A plataforma consolidou uma experiência de estudo acessível e responsiva, preparada para receber novos conteúdos e recursos de acompanhamento.',
            skills: ['React', 'Arquitetura frontend', 'UX para educação', 'Design responsivo'],
          },
        },
      ],
    },
    experience: [
      {
        role: 'Cargo',
        company: 'Empresa',
        period: 'Período',
        summary: 'Resumo da experiência profissional será adicionado posteriormente.',
      },
      {
        role: 'Cargo',
        company: 'Empresa',
        period: 'Período',
        summary: 'Resumo da experiência profissional será adicionado posteriormente.',
      },
    ],
    common: {
      featuredLink: 'Ver todos os projetos',
      email: 'Enviar e-mail',
      footer: 'Desenvolvido com React e curiosidade.',
      imageUnavailable: 'Imagem do projeto será adicionada em breve',
    },
  },
  en: {
    nav: { home: 'Home', about: 'About', projects: 'Projects' },
    home: {
      eyebrow: 'Software Engineer | Backend & Cloud',
      title: 'Engineering scalable backend systems',
      description:
        'I build APIs, integrations, and serverless architectures to create distributed systems running in production.',
      primaryAction: 'View projects',
      secondaryAction: 'Get in touch',
      specialtiesLabel: 'Expertise',
      specialtiesTitle: 'Technology applied to real problems',
      specialties: [
        {
          title: 'Backend Engineering',
          description: 'APIs and services built for clarity, reliability, and continuous evolution.',
          icon: 'backend',
        },
        {
          title: 'Cloud & AWS',
          description: 'Serverless architectures and automation designed to operate in the cloud.',
          icon: 'cloud',
        },
        {
          title: 'Distributed Systems & Integrations',
          description: 'Event-driven systems and integrations that create reliable workflows.',
          icon: 'systems',
        },
      ],
      featuredLabel: 'Featured projects',
      featuredTitle: 'A selection of my work',
      experienceLabel: 'Experience',
      experienceTitle: 'Continuous learning, practical delivery',
      experience:
        'My path combines development, automation, and systems integration. I seek to understand the context before choosing technology and value simple, sustainable solutions.',
      contactLabel: 'Contact',
      contactTitle: 'Shall we build something together?',
      contact: 'I am available to talk about projects, opportunities, and good ideas.',
    },
    about: {
      eyebrow: 'About me',
      title: 'Technology with curiosity, clarity, and purpose.',
      journeyLabel: 'Journey',
      journeyTitle: 'Building a complete perspective',
      journey: [
        'I am a developer interested in solving problems through technology. I enjoy understanding how every part of a system connects and how software can make people’s work easier.',
        'My path combines Python, cloud, integrations, and web development. I am currently deepening my experience with React and digital product development.',
      ],
      principlesLabel: 'Principles',
      principles: [
        ['Clarity', 'Solutions and communication should be easy to understand.'],
        ['Curiosity', 'Asking questions and investigating are essential parts of the work.'],
        ['Consistency', 'Quality comes from good decisions repeated every day.'],
      ],
      goalsLabel: 'Goals',
      goalsTitle: 'The next chapter',
      goals:
        'I want to keep growing as a developer, collaborate with diverse teams, and build products that create measurable impact for people and businesses.',
    },
    projects: {
      eyebrow: 'ENGINEERING PORTFOLIO',
      title: 'Building Systems That Solve Real Business Problems',
      description:
        'Backend, cloud, automation, and integration projects designed to solve real business challenges.',
      viewProject: 'View case study',
      backToProjects: 'Back to projects',
      challenge: 'Problem',
      solution: 'Solution',
      stack: 'Technologies',
      caseStudy: {
        architectureImage: 'System overview',
        architecture: 'Architecture',
        responsibility: 'My responsibility',
        requestFlow: 'Request flow',
        decisions: 'Technical decisions',
        challenges: 'Key challenges',
        results: 'Outcome',
        skills: 'Skills demonstrated',
      },
      items: [
        {
          slug: 'salesforce-integration',
          number: '01',
          title: 'Salesforce Integration',
          summary: 'Data and process integration for more efficient commercial operations.',
          challenge: 'Unify distributed information and reduce manual tasks across systems.',
          solution: 'Integration workflows that keep data synchronized and traceable.',
          stack: ['Salesforce', 'APIs', 'Integration'],
          imageAlt: 'Diagram of the Salesforce integration project',
          caseStudy: {
            responsibility: 'I designed and implemented the integration flow, defined data mappings, and organized failure handling to make synchronization observable and reliable.',
            architecture: 'The solution separates the data source, integration layer, and Salesforce. API communication keeps systems decoupled, while validation and execution records make every operation easier to trace.',
            requestFlow: ['Source system', 'Integration API', 'Validation and transformation', 'Salesforce'],
            challenges: ['Reconcile different data models', 'Prevent duplicate records during reprocessing', 'Trace failures without stopping the entire flow'],
            decisions: ['Centralize transformations in the integration layer', 'Use external identifiers to guarantee idempotency', 'Record the context and outcome of each synchronization'],
            result: 'The flow reduced manual work, improved commercial data consistency, and established a reliable foundation for additional integrations.',
            skills: ['Systems integration', 'API design', 'Data modeling', 'Observability'],
          },
        },
        {
          slug: 'python-aws-automation',
          number: '02',
          title: 'Python + AWS Automation',
          summary: 'Task automation and data processing using cloud services.',
          challenge: 'Repetitive processes consumed time and made scaling difficult.',
          solution: 'Python routines running on AWS to process and distribute data.',
          stack: ['Python', 'AWS', 'Automation'],
          imageAlt: 'Architecture of the automation built with Python and AWS',
          caseStudy: {
            responsibility: 'I implemented the Python routines, structured execution on AWS, and defined validation, logging, and reprocessing mechanisms for reliable operation.',
            architecture: 'The event-driven architecture receives a request, distributes work through a queue, and runs independent functions. Storage preserves inputs and outputs for auditing and reprocessing.',
            requestFlow: ['Input event', 'Amazon SQS', 'AWS Lambda', 'Storage and output'],
            challenges: ['Process variable workloads without manual intervention', 'Handle temporary failures in external services', 'Keep every execution traceable'],
            decisions: ['Use asynchronous queue-based processing', 'Create small functions with focused responsibilities', 'Apply controlled retries and a dead-letter queue'],
            result: 'The automation reduced time spent on repetitive tasks and enabled predictable processing at scale with improved operational visibility.',
            skills: ['Python', 'AWS Serverless', 'Event-driven systems', 'Automation'],
          },
        },
        {
          slug: 'melita-ai-agent',
          number: '03',
          title: 'Melita AI Agent',
          summary: 'An AI agent designed to support conversations and decisions.',
          challenge: 'Provide useful answers without losing conversation context.',
          solution: 'A goal-oriented agent with structured instructions and context.',
          stack: ['AI', 'Agents', 'Product'],
          imageAlt: 'Workflow of the Melita artificial intelligence agent',
          caseStudy: {
            responsibility: 'I structured the agent behavior, organized context sources, and implemented the conversation flow with validation for more consistent answers.',
            architecture: 'The application receives a message, retrieves relevant context, and builds a structured request for the model. The response is validated before returning to the interface and updating history.',
            requestFlow: ['Conversation interface', 'Agent orchestrator', 'Context and memory', 'Language model', 'User response'],
            challenges: ['Preserve context without adding conversation noise', 'Reduce inaccurate or off-goal responses', 'Balance quality, latency, and cost'],
            decisions: ['Separate instructions, memory, and user messages', 'Limit context to relevant content', 'Validate output before displaying it in the interface'],
            result: 'The agent produced more contextual and predictable interactions, providing a clear foundation for testing, evaluation, and product evolution.',
            skills: ['Prompt engineering', 'AI agents', 'Context architecture', 'Product development'],
          },
        },
        {
          slug: 'italian-learning-platform',
          number: '04',
          title: 'Italian learning platform',
          summary: 'A digital experience designed to make learning more accessible.',
          challenge: 'Organize content in a clear, progressive, and motivating way.',
          solution: 'A platform centered on each student’s experience and progress.',
          stack: ['Education', 'React', 'UX'],
          imageAlt: 'Interface of the Italian learning platform',
          caseStudy: {
            responsibility: 'I modeled the learning experience, developed the React interface, and organized content and progress structures to support gradual development.',
            architecture: 'The React interface consumes a content layer organized into modules. Application state tracks navigation and progress, with a structure ready for future API persistence.',
            requestFlow: ['React interface', 'Learning module', 'Lesson content', 'Student progress'],
            challenges: ['Organize content without overwhelming the interface', 'Keep the experience consistent across screen sizes', 'Represent progress in a simple and motivating way'],
            decisions: ['Split content into small progressive modules', 'Create reusable lesson and exercise components', 'Prioritize clear navigation and immediate feedback'],
            result: 'The platform established an accessible, responsive study experience ready to receive new content and progress-tracking features.',
            skills: ['React', 'Frontend architecture', 'Education UX', 'Responsive design'],
          },
        },
      ],
    },
    experience: [
      {
        role: 'Role',
        company: 'Company',
        period: 'Period',
        summary: 'The professional experience summary will be added later.',
      },
      {
        role: 'Role',
        company: 'Company',
        period: 'Period',
        summary: 'The professional experience summary will be added later.',
      },
    ],
    common: {
      featuredLink: 'View all projects',
      email: 'Send an email',
      footer: 'Built with React and curiosity.',
      imageUnavailable: 'Project image coming soon',
    },
  },
}
